### ISSUE TITLE
404 from code.google.com URLs in .gitmodules 

### ISSUE THREAD

**Issue by caktus-philip** [jbtule/keyczar-python2to3#4]
The [.gitmodules](https://github.com/jbtule/keyczar-python2to3/blob/master/.gitmodules) file references URLs like `https://code.google.com/r/jtuley-keyczar-testdata`, but they don't work anymore since the demise of Google Code.

**Comment by jbtule** [comment]
found a copy of it, and put it on github, and updated master.

**Comment by caktus-philip** [comment]
Thanks for the super-quick fix!
